swagger: "2.0"
info:
  version: "0.0.1"
  title: Restify Micro Service
# during dev, should point to your local machine
host: localhost:3030
# basePath prefixes all resource paths 
basePath: /v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /sample:
    # binds a127 app logic to a route
    x-swagger-router-controller: sample_controller
    get:
      summary: Get method for sample endpoint
      description: Returns JSON Object to the caller
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: limit
          in: query
          description: Limits the amount of results returned
          required: false
          type: number
        - name: offset
          in: query
          description: Pagination of the results
          required: false
          type: number
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Post method for sample endpoint
      description: Adds a new Object
      responses:
        200:
          description: OK
    put:
      summary: Put method for sample endpoint
      description: Updates an Object
      responses:
        200:
          description: OK
    
    delete:
      summary: Delete method for Sample endpoint
      description: Deletes an Object
      responses:
        200:
          description: OK
      
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
